### ISSUE TITLE
mutli-attach errors emitted when a pod moves to a new host

### ISSUE THREAD

**Issue by jhorwit2** [oracle/oci-volume-provisioner#102]
I deployed a stateful set and was playing around with draining the node that the stateful set was on. While doing that I noticed the following event. I'm fairly certain this is just a race condition between the detach event and pod being scheduled but it'd be nice to know for sure so I made this ticket to track researching that. Eventually the volume gets moved correctly, so this isn't a terminal error that prevents the pod from being moved. 

```
  Type     Reason                 Age   From                      Message
  ----     ------                 ----  ----                      -------
  Warning  FailedAttachVolume     1m    attachdetach-controller   Multi-Attach error for volume "<id>" Volume is already exclusively attached to one node and can't be attached to another
```

**Comment by garthy** [comment]
What version of kubernetes was this?

I've seen cases where the attach controller seems to get out of sync with
the kubelets and you see a bunch of flex operations that don't make sense.

It seems to sort itself out after around 30sec to a minute but it's not
optimal and would be great to know why this is happening.


If you see it happen next time can you grab the logs from the node kubelets
involved + flex volume and the KCM logs and it's flex volume attachment
logs.

**Comment by jhorwit2** [comment]
This cluster is 1.9.2. 

Yeah, it's not long; the pod is able to mount within a minute from what I've seen. I'm mainly just curious if we can make it better. I'm guessing this is a race between the scheduler and OCI detaching; if it is then we will probably just have to live with it.

**Comment by prydie** [comment]
Closing for now. Do reopen if you feel it warrants further attention 🙂
