### ISSUE TITLE
Authconfig structure is overloaded

### ISSUE THREAD

**Issue by owainlewis** [oracle/oci-volume-provisioner#106]
We should keep configuration consistent across projects. We are adding compartment and instance principal logic to the AuthConfig struct which doesn't make logical sense.

**Comment by harveylowndes** [comment]
I think that we should leave the AuthConfig alone, however we should move the instance principles flag out of the AuthConfig and into Config. Both Auth and UseInstancePrincipals can be made optional with the logic to validate one or the other exists.
