### ISSUE TITLE
Allow user to define minimum size for volumes

### ISSUE THREAD

**Issue by tjfontaine** [oracle/oci-volume-provisioner#120]
Currently, OCI does not allow the creation of block storage volumes of less than 50GiB.

Some helm charts don't allow users to (easily) override the size of volumes being requested.

As a result, consumption of said charts will fail to provision, because PVs of < 50GiB cannot be used. 

Users should have a way to specify that they wish to round up PV requests to a minimum, perhaps stored in a `ConfigMap`.

And then in our example deployment/docs we include that by default.

If it's done in a form of `roundVolumeClaimsUp: 50GiB` then if/when OCI supports smaller sizes this value can be resized by customers for new volumes.

Related to #109

**Comment by tjfontaine** [comment]
I'm not sure there's a great way to handle this at the provisioner layer.

We can change the value of the PV, but then K8S own reconciliation will constantly try and reprovision a PV with the matching resource size of the PVC. The provisioner can't change the PVC size to match, because resource size field is immutable by the time the provisioner can operate on it.

You could use a mutating webhook to change it as is demonstrated [here](http://github.com/tjfontaine/round-up-storage-claim/), but it's likely that other external reconciliation processes/controllers would fail because the size doesn't match what they had requested (i.e. statefulset controllers/operators).

The _only_  option that works is to change the value passed to the OCI API, which leaves the PVC and PV reporting what the user originally asked for. But if the user then queries the OCI API they'll see our lies exposed.

**Comment by owainlewis** [comment]
You can modify the value returned to the user at the provisioner level. Kubernetes returns the information provided by the volume provisioner. One implementation option is to add a parameter to the storage class to enable rounding logic.

By default this parameter doesn't exist but you can delete and recreate the storage class.

```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: oci
provisioner: oracle.com/oci
parameters:
  minVolumeSizeMB: "51200"
```
