### ISSUE TITLE
Don't rely on storage class names to dispatch custom logic

### ISSUE THREAD

**Issue by owainlewis** [oracle/oci-volume-provisioner#131]
We currently rely on the name of a storage class to dispatch logic (oci-ext3 etc). We should change this to look at the storage class provisioner parameter because the names of storage classes should be independent of any underlying logic.

**Comment by jhorwit2** [comment]
+1 

This makes storage classes largely useless. For example, storage classes should be able to define mount options, which may not apply to all PVs created; however, because we force names of storage classes we can't create multiple.

**Comment by MadalinaPatrichi** [comment]
Fixed in: https://github.com/oracle/oci-volume-provisioner/pull/154
