### ISSUE TITLE
Pods get blocked when the volume is detached

### ISSUE THREAD

**Issue by ashokkkannan** [oracle/oci-volume-provisioner#140]
We are using dynamic block volume based persistence(provisioned by OCI Volume provisioner) for a Statefulset in OKE(managed) cluster. When the volume gets detached from the instance the pod becomes undeletable as any process that tries to read/write to the path mounted on the volume gets blocked. They don't respond to any kill signals and hence docker is not able to kill the container. Also even when the volume is reattached by the provisioner the volume is still not accessible.

Steps to reproduce:
1. Create a statefulset with Dynamic PV and OCI  Storage class
2. Wait for the Pods to come up with the PV provisioned by OCI-volume-provisioner.
3. In the OCI console detach the Volume used by the pod from the instance without running iSCSI detach commands
4. Wait for the  OCI-volume-provisioner to attach the volume back to the instance.
5. Try deleting the pod. `kubectl delete pod <POD_NAME>`. Though k8s says the pod is deleted you can still see the pod running.

Expected Behaviour:
1. When the volume is detached the process shouldn't get blocked. 
2. The pod should be deletable. It is possible that the health check(probes) might start failing as the disk is not available for the process to read/write. But since the process gets blocked indefinitely it would not be possible for the Kubernetes or the user to delete the pod. 
3. When the provisioner attaches the disk back to the instance it should be accessible from the pod.

**Comment by ashokkkannan** [comment]
When provisioner reattach a volume the iSCSI TCP Endpoint address is getting changed. But the old iSCSI session is still active and keeps trying to connect using the old Endpoint address. Once we terminate this old session then all the blocked processes gets unblocked(and terminates).  The only the pods become deletable.

The TCP endpoint and the device ID (example: /dev/sdb) changes when the OCI reattach the disk. Hence ideally the provisioner might be required to do 
* Terminate the old session as there is a change in the TCP endpoint
* unmount the filesystem ( when the session is terminated the pod might die on its own and maybe docker unmount the volume. I'm not sure if this happens in all scenarios)
* Create a new iSCSI session and mount the file system backed by the new device ID.

**Comment by jhorwit2** [comment]
This seems like an upstream issue. 

The provisioner does not handle mounting or unmounting file systems. The provisioners job is provision PV's base don PVCs. The flex volume driver, which does handle the mount and unmounts only does so after being called by the kubelet.

**Comment by ashokkkannan** [comment]
I'm not much familiar with flex volume driver, but I assume attaching/detaching of the disk is something specific to OCI. I'm not sure which component initiates it. But whenever a disk is reattached the endpoint changes(again this is specific to OCI) which requires the iSCI connection to be terminated and a new connection to be established. I'm not sure if upstream might want to handle this as this issue seem specific to the way OCI block volume is implemented.

**Comment by jhorwit2** [comment]
https://github.com/oracle/oci-flexvolume-driver

Is where you should reopen this ticket. That component handles attaching and detaching volumes.
