### ISSUE TITLE
Improve the examples 

### ISSUE THREAD

**Issue by andy-page** [oracle/oci-volume-provisioner#149]
There are some things in the examples directory that shouldn't be there. Specifically templates used for testing.

Rather than put examples in separate files, it would be easier for users if the examples were all in a single YAML file.

**Comment by prydie** [comment]
Hi Andy, 

The testing templates should certainly be moved, however, the examples are separated into indivtual files so that the resources they represent can be easily created individually. This is a common pattern throughout the ecosystem and it’s something I would prefer we retained.

**Comment by andy-page** [comment]
hi Andrew, actually @owainlewis logged this from my terminal. @owainlewis, can you respond pls.

**Comment by owainlewis** [comment]
Yeah I just felt it might be easier to have a single file example. Not a big deal. The main thing is getting the templates out of that directory.

**Comment by MadalinaPatrichi** [comment]
This was resolved in the FSS feature PR (the move of the templates files).Do we need to do anything else to be able to close this?
