### ISSUE TITLE
Tag resources created in OCI

### ISSUE THREAD

**Issue by owainlewis** [oracle/oci-volume-provisioner#47]
We could make use of resource tagging in OCI to track which resources are created by the volume provisioner. The goal here would be to give the ability to see which resources are owned by a particular cluster which might be useful for debugging and introspection.

kubernetes.io/clusters/<CLUSTER_ID>={owned | }

See: https://docs.us-phoenix-1.oraclecloud.com/Content/Identity/Concepts/taggingoverview.htm

**Comment by harveylowndes** [comment]
@owainlewis I wanted to look at this issue, however, as @prydie  found, we seem to be blocked by this issue. https://github.com/kubernetes/federation/issues/132
