### ISSUE TITLE
Support creating block volume based on a backup

### ISSUE THREAD

**Issue by dansimone** [oracle/oci-volume-provisioner#92]
It would be useful to be able to specify as metadata to the PVC the coordinates of an OCI Block Volume backup, and have the oci-volume-provisioner create its Block Volume based on that backup.

**Comment by owainlewis** [comment]
Thanks @dansimone we'll discuss this week.

**Comment by owainlewis** [comment]
An alternative solution would be to do this manually via the UI. We will hold off on implementing this feature and document how it can be achieved manually.

**Comment by owainlewis** [comment]
@dansimone this change adds the ability to create a new block volume from an existing block volume.

https://github.com/oracle/oci-volume-provisioner/commit/92a72e6989ebe189b4ef944c499bfd308ea0799c
