### ISSUE TITLE
Volume prefix should append a hyphen if missing to match the CCM

### ISSUE THREAD

**Issue by jhorwit2** [oracle/oci-volume-provisioner#99]
If I have a volume claim named `foo` and put set the prefix env var to `bar`, then my display name in OCI will be `barfoo`. It should be `bar-foo` which matches the CCM logic. 

https://github.com/oracle/oci-cloud-controller-manager/blob/3d533ef04eb8233ddc3a730c8281742b4d5ae03a/pkg/oci/load_balancer_util.go#L412

**Comment by alapidas** [comment]
Should make sure upgrading after this change dorsnt break existing claims

**Comment by MadalinaPatrichi** [comment]
Issue is not fixed, the prefix is not actually being used when creating the volume in: Append hyphen to volume name prefix #107
